name: Mindustry Server

on:
  workflow_dispatch:

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
    - name: Download Mindustry Server
      run: |
        mkdir server && cd server
        wget -O server.jar https://github.com/Anuken/Mindustry/releases/latest/download/server-release.jar

    - name: Download Playit Binary
      run: |
        wget -O playit https://github.com/playit-cloud/playit-agent/releases/latest/download/playit-linux-amd64
        chmod +x playit

    - name: Run Mindustry & Playit
      run: |
        sudo ./playit > playit.log 2>&1 &
        sleep 5
        cat playit.log
        cd server
        java -jar server.jar
